//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BusinessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SocialNetEntities : DbContext
    {
        public SocialNetEntities()
            : base("name=SocialNetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ale_alert> ale_alert { get; set; }
        public virtual DbSet<cou_country> cou_country { get; set; }
        public virtual DbSet<dic_dictionary> dic_dictionary { get; set; }
        public virtual DbSet<ent_entity> ent_entity { get; set; }
        public virtual DbSet<lan_language> lan_language { get; set; }
        public virtual DbSet<lik_like> lik_like { get; set; }
        public virtual DbSet<rel_relationship> rel_relationship { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<evn_event> evn_event { get; set; }
        public virtual DbSet<blo_blob> blo_blob { get; set; }
    
        public virtual ObjectResult<SP_MAIL_RESETPASS_Result> SP_MAIL_RESETPASS(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_MAIL_RESETPASS_Result>("SP_MAIL_RESETPASS", idParameter);
        }
    
        public virtual ObjectResult<SP_FIND_FRIENDS_Result> SP_FIND_FRIENDS(string searchstr, Nullable<long> entIdSession, Nullable<int> intPageSize)
        {
            var searchstrParameter = searchstr != null ?
                new ObjectParameter("searchstr", searchstr) :
                new ObjectParameter("searchstr", typeof(string));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FIND_FRIENDS_Result>("SP_FIND_FRIENDS", searchstrParameter, entIdSessionParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_COUNT_FRIEND_Result> SP_GET_COUNT_FRIEND(Nullable<long> entId, Nullable<long> entIdSession)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_COUNT_FRIEND_Result>("SP_GET_COUNT_FRIEND", entIdParameter, entIdSessionParameter);
        }
    
        public virtual ObjectResult<SP_GET_COUNT_GROUP_Result> SP_GET_COUNT_GROUP(Nullable<long> entIdGroup, Nullable<long> entId)
        {
            var entIdGroupParameter = entIdGroup.HasValue ?
                new ObjectParameter("entIdGroup", entIdGroup) :
                new ObjectParameter("entIdGroup", typeof(long));
    
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_COUNT_GROUP_Result>("SP_GET_COUNT_GROUP", entIdGroupParameter, entIdParameter);
        }
    
        public virtual ObjectResult<SP_FIND_GROUPS_Result> SP_FIND_GROUPS(string searchstr, Nullable<long> entIdSession, Nullable<int> intPageSize)
        {
            var searchstrParameter = searchstr != null ?
                new ObjectParameter("searchstr", searchstr) :
                new ObjectParameter("searchstr", typeof(string));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FIND_GROUPS_Result>("SP_FIND_GROUPS", searchstrParameter, entIdSessionParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_ALERTS_Result> SP_GET_ALERTS(Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_ALERTS_Result>("SP_GET_ALERTS", entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_GROUPSFRIEND_Result> SP_GET_GROUPSFRIEND(Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_GROUPSFRIEND_Result>("SP_GET_GROUPSFRIEND", entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_BADGES_Result> SP_GET_BADGES(Nullable<long> entIdSession)
        {
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_BADGES_Result>("SP_GET_BADGES", entIdSessionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_GET_COUNT_COMPANY(Nullable<long> entId)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GET_COUNT_COMPANY", entIdParameter);
        }
    
        public virtual ObjectResult<SP_FIND_COMPANIES_Result> SP_FIND_COMPANIES(string searchstr, Nullable<long> entIdSession, Nullable<int> intPageSize)
        {
            var searchstrParameter = searchstr != null ?
                new ObjectParameter("searchstr", searchstr) :
                new ObjectParameter("searchstr", typeof(string));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_FIND_COMPANIES_Result>("SP_FIND_COMPANIES", searchstrParameter, entIdSessionParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_COMPANIES_Result> SP_GET_COMPANIES(Nullable<long> entIdCompany, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var entIdCompanyParameter = entIdCompany.HasValue ?
                new ObjectParameter("entIdCompany", entIdCompany) :
                new ObjectParameter("entIdCompany", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_COMPANIES_Result>("SP_GET_COMPANIES", entIdCompanyParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_COMMENTS_Result> SP_GET_COMMENTS(Nullable<long> evnId, Nullable<long> evnIdTarget, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var evnIdParameter = evnId.HasValue ?
                new ObjectParameter("evnId", evnId) :
                new ObjectParameter("evnId", typeof(long));
    
            var evnIdTargetParameter = evnIdTarget.HasValue ?
                new ObjectParameter("evnIdTarget", evnIdTarget) :
                new ObjectParameter("evnIdTarget", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_COMMENTS_Result>("SP_GET_COMMENTS", evnIdParameter, evnIdTargetParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_GALLERIES_Result> SP_GET_GALLERIES(Nullable<long> evnId, Nullable<long> entId, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var evnIdParameter = evnId.HasValue ?
                new ObjectParameter("evnId", evnId) :
                new ObjectParameter("evnId", typeof(long));
    
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_GALLERIES_Result>("SP_GET_GALLERIES", evnIdParameter, entIdParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_POSTS_Result> SP_GET_POSTS(Nullable<long> evnId, Nullable<long> entId, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize, Nullable<int> typeEvent)
        {
            var evnIdParameter = evnId.HasValue ?
                new ObjectParameter("evnId", evnId) :
                new ObjectParameter("evnId", typeof(long));
    
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            var typeEventParameter = typeEvent.HasValue ?
                new ObjectParameter("typeEvent", typeEvent) :
                new ObjectParameter("typeEvent", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_POSTS_Result>("SP_GET_POSTS", evnIdParameter, entIdParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter, typeEventParameter);
        }
    
        public virtual ObjectResult<SP_GET_LIST_ENTITIES_Result> SP_GET_LIST_ENTITIES(Nullable<long> entId)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_LIST_ENTITIES_Result>("SP_GET_LIST_ENTITIES", entIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_PROFILE_Result> SP_GET_PROFILE(Nullable<long> entId)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_PROFILE_Result>("SP_GET_PROFILE", entIdParameter);
        }
    
        public virtual ObjectResult<SP_GET_COUNT_MEMBER_Result> SP_GET_COUNT_MEMBER(Nullable<long> entId, Nullable<long> entIdSession)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_COUNT_MEMBER_Result>("SP_GET_COUNT_MEMBER", entIdParameter, entIdSessionParameter);
        }
    
        public virtual ObjectResult<SP_GET_GROUPS_Result> SP_GET_GROUPS(Nullable<long> entIdGroup, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize, Nullable<bool> accepted, Nullable<bool> rejected, Nullable<bool> suggested, Nullable<int> typeAction)
        {
            var entIdGroupParameter = entIdGroup.HasValue ?
                new ObjectParameter("entIdGroup", entIdGroup) :
                new ObjectParameter("entIdGroup", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            var acceptedParameter = accepted.HasValue ?
                new ObjectParameter("accepted", accepted) :
                new ObjectParameter("accepted", typeof(bool));
    
            var rejectedParameter = rejected.HasValue ?
                new ObjectParameter("rejected", rejected) :
                new ObjectParameter("rejected", typeof(bool));
    
            var suggestedParameter = suggested.HasValue ?
                new ObjectParameter("suggested", suggested) :
                new ObjectParameter("suggested", typeof(bool));
    
            var typeActionParameter = typeAction.HasValue ?
                new ObjectParameter("typeAction", typeAction) :
                new ObjectParameter("typeAction", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_GROUPS_Result>("SP_GET_GROUPS", entIdGroupParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter, acceptedParameter, rejectedParameter, suggestedParameter, typeActionParameter);
        }
    
        public virtual ObjectResult<SP_GET_FRIENDS_Result> SP_GET_FRIENDS(Nullable<long> entId, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_FRIENDS_Result>("SP_GET_FRIENDS", entIdParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_MEMBERS_Result> SP_GET_MEMBERS(Nullable<long> entId, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_MEMBERS_Result>("SP_GET_MEMBERS", entIdParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    
        public virtual ObjectResult<SP_GET_FOLLOWERS_Result> SP_GET_FOLLOWERS(Nullable<long> entId, Nullable<long> entIdSession, Nullable<int> intLastId, Nullable<int> intPageSize)
        {
            var entIdParameter = entId.HasValue ?
                new ObjectParameter("entId", entId) :
                new ObjectParameter("entId", typeof(long));
    
            var entIdSessionParameter = entIdSession.HasValue ?
                new ObjectParameter("entIdSession", entIdSession) :
                new ObjectParameter("entIdSession", typeof(long));
    
            var intLastIdParameter = intLastId.HasValue ?
                new ObjectParameter("intLastId", intLastId) :
                new ObjectParameter("intLastId", typeof(int));
    
            var intPageSizeParameter = intPageSize.HasValue ?
                new ObjectParameter("intPageSize", intPageSize) :
                new ObjectParameter("intPageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_FOLLOWERS_Result>("SP_GET_FOLLOWERS", entIdParameter, entIdSessionParameter, intLastIdParameter, intPageSizeParameter);
        }
    }
}
