//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_dictionary
    {
        public long dic_id { get; set; }
        public string dic_table { get; set; }
        public string dic_storeValue { get; set; }
        public string dic_displayValue { get; set; }
        public Nullable<int> dic_order { get; set; }
        public bool dic_enabled { get; set; }
    }
}
