//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class evn_event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evn_event()
        {
            this.lik_like = new HashSet<lik_like>();
        }
    
        public long evn_id { get; set; }
        public Nullable<long> evn_idTarget { get; set; }
        public Nullable<bool> evn_system { get; set; }
        public Nullable<long> ent_idDo { get; set; }
        public Nullable<long> ent_idDd { get; set; }
        public Nullable<int> evn_typeEvent { get; set; }
        public string evn_comment { get; set; }
        public Nullable<long> blo_idMaterial { get; set; }
        public Nullable<int> evn_visibility { get; set; }
        public string evn_locationString { get; set; }
        public string evn_locationCode { get; set; }
        public Nullable<decimal> evn_latitude { get; set; }
        public Nullable<decimal> evn_longitude { get; set; }
        public Nullable<int> evn_externalType { get; set; }
        public string evn_externalLink { get; set; }
        public Nullable<System.DateTime> evn_timestampModified { get; set; }
        public System.DateTime evn_timestampCreated { get; set; }
        public bool evn_enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lik_like> lik_like { get; set; }
    }
}
