//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class lik_like
    {
        public long lik_id { get; set; }
        public Nullable<long> ent_id { get; set; }
        public Nullable<long> evn_id { get; set; }
        public Nullable<int> lik_typeLike { get; set; }
        public System.DateTime lik_timestampCreated { get; set; }
        public bool lik_enabled { get; set; }
    
        public virtual ent_entity ent_entity { get; set; }
        public virtual evn_event evn_event { get; set; }
    }
}
