//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_relationship
    {
        public long rel_id { get; set; }
        public Nullable<long> ent_idDo { get; set; }
        public Nullable<long> ent_idDd { get; set; }
        public Nullable<long> ent_idDr { get; set; }
        public Nullable<System.DateTime> rel_timestampSuggested { get; set; }
        public Nullable<bool> rel_suggested { get; set; }
        public Nullable<System.DateTime> rel_timestampOffered { get; set; }
        public Nullable<bool> rel_offered { get; set; }
        public Nullable<System.DateTime> rel_timestampResponse { get; set; }
        public Nullable<bool> rel_accepted { get; set; }
        public Nullable<bool> rel_rejected { get; set; }
        public Nullable<bool> rel_blocked { get; set; }
        public Nullable<bool> rel_following { get; set; }
        public Nullable<System.DateTime> rel_timestampModified { get; set; }
        public System.DateTime rel_timestampCreated { get; set; }
        public bool rel_enabled { get; set; }
    
        public virtual ent_entity ent_entity { get; set; }
        public virtual ent_entity ent_entity1 { get; set; }
        public virtual ent_entity ent_entity2 { get; set; }
    }
}
