//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alert() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Resource.Alert", typeof(Alert).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} comento una publicación tuya..
        /// </summary>
        public static string commentPost {
            get {
                return ResourceManager.GetString("commentPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} want to be your friend..
        /// </summary>
        public static string friendSuggest {
            get {
                return ResourceManager.GetString("friendSuggest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2} want invite to participe to group {1}..
        /// </summary>
        public static string inviteJoinMember {
            get {
                return ResourceManager.GetString("inviteJoinMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} starts to following..
        /// </summary>
        public static string joinFollower {
            get {
                return ResourceManager.GetString("joinFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} want to join to {1} group..
        /// </summary>
        public static string joinMember {
            get {
                return ResourceManager.GetString("joinMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} subio una publicación en tu muro..
        /// </summary>
        public static string postFriend {
            get {
                return ResourceManager.GetString("postFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} subio una publicación en el grupo {1}..
        /// </summary>
        public static string postGroup {
            get {
                return ResourceManager.GetString("postGroup", resourceCulture);
            }
        }
    }
}
