//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Resource.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation already has been ready..
        /// </summary>
        public static string alreadySave {
            get {
                return ResourceManager.GetString("alreadySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field required.
        /// </summary>
        public static string errorFieldRequired {
            get {
                return ResourceManager.GetString("errorFieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format incorrect.
        /// </summary>
        public static string errorIncorrectFormat {
            get {
                return ResourceManager.GetString("errorIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters max.
        /// </summary>
        public static string errorNmaxlength {
            get {
                return ResourceManager.GetString("errorNmaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least {0} characters.
        /// </summary>
        public static string errorNminlength {
            get {
                return ResourceManager.GetString("errorNminlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords new are different.
        /// </summary>
        public static string errorPasswordDiferent {
            get {
                return ResourceManager.GetString("errorPasswordDiferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Your image.
        /// </summary>
        public static string errorUploadFileNotFound {
            get {
                return ResourceManager.GetString("errorUploadFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is too large, maximum allowed size is: {0}.
        /// </summary>
        public static string errorUploadSizeLong {
            get {
                return ResourceManager.GetString("errorUploadSizeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please file of type: {0}.
        /// </summary>
        public static string errorUploadWrongFormat {
            get {
                return ResourceManager.GetString("errorUploadWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It sent an email.
        /// </summary>
        public static string loginConfirm {
            get {
                return ResourceManager.GetString("loginConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string loginError1 {
            get {
                return ResourceManager.GetString("loginError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not exist.
        /// </summary>
        public static string loginError2 {
            get {
                return ResourceManager.GetString("loginError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered.
        /// </summary>
        public static string loginError3 {
            get {
                return ResourceManager.GetString("loginError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo expiro para cambiar la contraseña.
        /// </summary>
        public static string loginError4 {
            get {
                return ResourceManager.GetString("loginError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña actual no coincide.
        /// </summary>
        public static string loginError5 {
            get {
                return ResourceManager.GetString("loginError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña nueva no puede ser igual a la actual.
        /// </summary>
        public static string loginError6 {
            get {
                return ResourceManager.GetString("loginError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success transaction.
        /// </summary>
        public static string notifyOK {
            get {
                return ResourceManager.GetString("notifyOK", resourceCulture);
            }
        }
    }
}
