//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web_Resource.Site", typeof(Site).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string btnAddFriend {
            get {
                return ResourceManager.GetString("btnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string btnAddGroup {
            get {
                return ResourceManager.GetString("btnAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar Foto.
        /// </summary>
        public static string btnChangePhoto {
            get {
                return ResourceManager.GetString("btnChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        public static string btnCreateGroup {
            get {
                return ResourceManager.GetString("btnCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Valores.
        /// </summary>
        public static string btnEditValues {
            get {
                return ResourceManager.GetString("btnEditValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish edit.
        /// </summary>
        public static string btnFinishEdit {
            get {
                return ResourceManager.GetString("btnFinishEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow organization.
        /// </summary>
        public static string btnJoinCompany {
            get {
                return ResourceManager.GetString("btnJoinCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join to group.
        /// </summary>
        public static string btnJoinGroup {
            get {
                return ResourceManager.GetString("btnJoinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this account.
        /// </summary>
        public static string btnRemoveAccount {
            get {
                return ResourceManager.GetString("btnRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this group.
        /// </summary>
        public static string btnRemoveGroup {
            get {
                return ResourceManager.GetString("btnRemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string btnShare {
            get {
                return ResourceManager.GetString("btnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest friend.
        /// </summary>
        public static string btnSuggestFriend {
            get {
                return ResourceManager.GetString("btnSuggestFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggest group.
        /// </summary>
        public static string btnSuggestGroup {
            get {
                return ResourceManager.GetString("btnSuggestGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string lblAnonymous {
            get {
                return ResourceManager.GetString("lblAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The followers can to be post in own wall.
        /// </summary>
        public static string lblCanPostWall {
            get {
                return ResourceManager.GetString("lblCanPostWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share as anonymous.
        /// </summary>
        public static string lblCheckAnonymous {
            get {
                return ResourceManager.GetString("lblCheckAnonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to add a picture.
        /// </summary>
        public static string lblClickPhoto {
            get {
                return ResourceManager.GetString("lblClickPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string lblCreateDate {
            get {
                return ResourceManager.GetString("lblCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a picture here.
        /// </summary>
        public static string lblDragPhoto {
            get {
                return ResourceManager.GetString("lblDragPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has changed his profile photo.
        /// </summary>
        public static string lblEventUser1 {
            get {
                return ResourceManager.GetString("lblEventUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has changed his cover picture.
        /// </summary>
        public static string lblEventUser2 {
            get {
                return ResourceManager.GetString("lblEventUser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shared a video.
        /// </summary>
        public static string lblEventUser3 {
            get {
                return ResourceManager.GetString("lblEventUser3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has created this gallery.
        /// </summary>
        public static string lblEventUser4 {
            get {
                return ResourceManager.GetString("lblEventUser4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follower.
        /// </summary>
        public static string lblFollower {
            get {
                return ResourceManager.GetString("lblFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        public static string lblGroupName {
            get {
                return ResourceManager.GetString("lblGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string lblInputBirth {
            get {
                return ResourceManager.GetString("lblInputBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origen country.
        /// </summary>
        public static string lblInputCountry {
            get {
                return ResourceManager.GetString("lblInputCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblInputEmail {
            get {
                return ResourceManager.GetString("lblInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblInputFirstName {
            get {
                return ResourceManager.GetString("lblInputFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblInputGender {
            get {
                return ResourceManager.GetString("lblInputGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lblInputLanguage {
            get {
                return ResourceManager.GetString("lblInputLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblInputLastName {
            get {
                return ResourceManager.GetString("lblInputLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube URL.
        /// </summary>
        public static string lblInputLinkYoutube {
            get {
                return ResourceManager.GetString("lblInputLinkYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string lblInputNewPassword {
            get {
                return ResourceManager.GetString("lblInputNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string lblInputOldPassword {
            get {
                return ResourceManager.GetString("lblInputOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblInputPassword {
            get {
                return ResourceManager.GetString("lblInputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a new notice for share?.
        /// </summary>
        public static string lblInputPost {
            get {
                return ResourceManager.GetString("lblInputPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to edit post?.
        /// </summary>
        public static string lblInputPostEdit {
            get {
                return ResourceManager.GetString("lblInputPostEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a notice for {0}?.
        /// </summary>
        public static string lblInputPostOther {
            get {
                return ResourceManager.GetString("lblInputPostOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string lblInputRepeatPassword {
            get {
                return ResourceManager.GetString("lblInputRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to member.
        /// </summary>
        public static string lblMember {
            get {
                return ResourceManager.GetString("lblMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close [Esc].
        /// </summary>
        public static string lblPopupClose {
            get {
                return ResourceManager.GetString("lblPopupClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string lblPopupLoading {
            get {
                return ResourceManager.GetString("lblPopupLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your password for can remove this account.
        /// </summary>
        public static string lblRemoveAccount {
            get {
                return ResourceManager.GetString("lblRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send mail again.
        /// </summary>
        public static string lnkChangePassSendMail {
            get {
                return ResourceManager.GetString("lnkChangePassSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to wall.
        /// </summary>
        public static string lnkGoWall {
            get {
                return ResourceManager.GetString("lnkGoWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget my password.
        /// </summary>
        public static string lnkRecoverPass {
            get {
                return ResourceManager.GetString("lnkRecoverPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string lnkSignup {
            get {
                return ResourceManager.GetString("lnkSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar amistad.
        /// </summary>
        public static string mnuAcceptFriend {
            get {
                return ResourceManager.GetString("mnuAcceptFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept participation.
        /// </summary>
        public static string mnuAcceptGroup {
            get {
                return ResourceManager.GetString("mnuAcceptGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string mnuBlock {
            get {
                return ResourceManager.GetString("mnuBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel request.
        /// </summary>
        public static string mnuCancelRequest {
            get {
                return ResourceManager.GetString("mnuCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close session.
        /// </summary>
        public static string mnuCloseSession {
            get {
                return ResourceManager.GetString("mnuCloseSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit post.
        /// </summary>
        public static string mnuEditPost {
            get {
                return ResourceManager.GetString("mnuEditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive notification.
        /// </summary>
        public static string mnuFollowFriend {
            get {
                return ResourceManager.GetString("mnuFollowFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View group activity.
        /// </summary>
        public static string mnuFollowGroup {
            get {
                return ResourceManager.GetString("mnuFollowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public wall.
        /// </summary>
        public static string mnuHome {
            get {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give participation.
        /// </summary>
        public static string mnuJoinRequest {
            get {
                return ResourceManager.GetString("mnuJoinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline friendship.
        /// </summary>
        public static string mnuRejectFriend {
            get {
                return ResourceManager.GetString("mnuRejectFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decline invitation.
        /// </summary>
        public static string mnuRejectGroup {
            get {
                return ResourceManager.GetString("mnuRejectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from my followers.
        /// </summary>
        public static string mnuRemoveFollower {
            get {
                return ResourceManager.GetString("mnuRemoveFollower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from my friends.
        /// </summary>
        public static string mnuRemoveFriend {
            get {
                return ResourceManager.GetString("mnuRemoveFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from my groups.
        /// </summary>
        public static string mnuRemoveGroup {
            get {
                return ResourceManager.GetString("mnuRemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove member group.
        /// </summary>
        public static string mnuRemoveMember {
            get {
                return ResourceManager.GetString("mnuRemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove post.
        /// </summary>
        public static string mnuRemovePost {
            get {
                return ResourceManager.GetString("mnuRemovePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string mnuUnBlock {
            get {
                return ResourceManager.GetString("mnuUnBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No receive notification.
        /// </summary>
        public static string mnuUnFollowFriend {
            get {
                return ResourceManager.GetString("mnuUnFollowFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No receive notification.
        /// </summary>
        public static string mnuUnFollowGroup {
            get {
                return ResourceManager.GetString("mnuUnFollowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not follow.
        /// </summary>
        public static string mnuUnLinkCompany {
            get {
                return ResourceManager.GetString("mnuUnLinkCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not participe.
        /// </summary>
        public static string mnuUnLinkGroup {
            get {
                return ResourceManager.GetString("mnuUnLinkGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string navCompanies {
            get {
                return ResourceManager.GetString("navCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string navFollowers {
            get {
                return ResourceManager.GetString("navFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string navFriends {
            get {
                return ResourceManager.GetString("navFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string navGroups {
            get {
                return ResourceManager.GetString("navGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string navMembers {
            get {
                return ResourceManager.GetString("navMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string navPhotos {
            get {
                return ResourceManager.GetString("navPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string navPosts {
            get {
                return ResourceManager.GetString("navPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string navProfile {
            get {
                return ResourceManager.GetString("navProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string navVideos {
            get {
                return ResourceManager.GetString("navVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search organizations.
        /// </summary>
        public static string plaSearchCompany {
            get {
                return ResourceManager.GetString("plaSearchCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search group.
        /// </summary>
        public static string plaSearchGroup {
            get {
                return ResourceManager.GetString("plaSearchGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching organizations....
        /// </summary>
        public static string plaSearchingCompany {
            get {
                return ResourceManager.GetString("plaSearchingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for group....
        /// </summary>
        public static string plaSearchingGroup {
            get {
                return ResourceManager.GetString("plaSearchingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for people....
        /// </summary>
        public static string plaSearchingPeople {
            get {
                return ResourceManager.GetString("plaSearchingPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found records.
        /// </summary>
        public static string plaSearchNotFound {
            get {
                return ResourceManager.GetString("plaSearchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search people.
        /// </summary>
        public static string plaSearchPeople {
            get {
                return ResourceManager.GetString("plaSearchPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow organization.
        /// </summary>
        public static string tabCompany1 {
            get {
                return ResourceManager.GetString("tabCompany1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All followers.
        /// </summary>
        public static string tabFollower1 {
            get {
                return ResourceManager.GetString("tabFollower1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everybody.
        /// </summary>
        public static string tabFriend1 {
            get {
                return ResourceManager.GetString("tabFriend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications sent.
        /// </summary>
        public static string tabFriend2 {
            get {
                return ResourceManager.GetString("tabFriend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications received.
        /// </summary>
        public static string tabFriend3 {
            get {
                return ResourceManager.GetString("tabFriend3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your groups.
        /// </summary>
        public static string tabGroup1 {
            get {
                return ResourceManager.GetString("tabGroup1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups Suggested.
        /// </summary>
        public static string tabGroup2 {
            get {
                return ResourceManager.GetString("tabGroup2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend&apos;s groups.
        /// </summary>
        public static string tabGroup3 {
            get {
                return ResourceManager.GetString("tabGroup3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string tabLogin1 {
            get {
                return ResourceManager.GetString("tabLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string tabLogin2 {
            get {
                return ResourceManager.GetString("tabLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All members.
        /// </summary>
        public static string tabMember1 {
            get {
                return ResourceManager.GetString("tabMember1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string titAddGroup {
            get {
                return ResourceManager.GetString("titAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string titChangePass {
            get {
                return ResourceManager.GetString("titChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company data.
        /// </summary>
        public static string titCompanyData {
            get {
                return ResourceManager.GetString("titCompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Photo.
        /// </summary>
        public static string titCoverPhoto {
            get {
                return ResourceManager.GetString("titCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends of.
        /// </summary>
        public static string titFriend {
            get {
                return ResourceManager.GetString("titFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group data.
        /// </summary>
        public static string titGroupData {
            get {
                return ResourceManager.GetString("titGroupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group photo.
        /// </summary>
        public static string titGroupPhoto {
            get {
                return ResourceManager.GetString("titGroupPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group.
        /// </summary>
        public static string titGroupRemove {
            get {
                return ResourceManager.GetString("titGroupRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string titLogin1 {
            get {
                return ResourceManager.GetString("titLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string titLogin2 {
            get {
                return ResourceManager.GetString("titLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover password.
        /// </summary>
        public static string titLogin3 {
            get {
                return ResourceManager.GetString("titLogin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm action.
        /// </summary>
        public static string titMsgConfirm {
            get {
                return ResourceManager.GetString("titMsgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string titPersonalData {
            get {
                return ResourceManager.GetString("titPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile photo.
        /// </summary>
        public static string titProfilePhoto {
            get {
                return ResourceManager.GetString("titProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Account.
        /// </summary>
        public static string titProfileRemove {
            get {
                return ResourceManager.GetString("titProfileRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string titSecurity {
            get {
                return ResourceManager.GetString("titSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete all data to create a group..
        /// </summary>
        public static string txtAddGroup {
            get {
                return ResourceManager.GetString("txtAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your old password and input the new password..
        /// </summary>
        public static string txtChangePass {
            get {
                return ResourceManager.GetString("txtChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo para cambiar la contraseña expiro. Por favor, envíe nuevamente el mail para cambiar su contraseña..
        /// </summary>
        public static string txtChangePassExpired {
            get {
                return ResourceManager.GetString("txtChangePassExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña se cambio satisfactoriamente..
        /// </summary>
        public static string txtChangePassSuccess {
            get {
                return ResourceManager.GetString("txtChangePassSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete with your email and password to access the net..
        /// </summary>
        public static string txtLogin1 {
            get {
                return ResourceManager.GetString("txtLogin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete all data to create a person account..
        /// </summary>
        public static string txtLogin2 {
            get {
                return ResourceManager.GetString("txtLogin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email account to retrieve your password..
        /// </summary>
        public static string txtLogin3 {
            get {
                return ResourceManager.GetString("txtLogin3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete all data to create a company account..
        /// </summary>
        public static string txtLogin4 {
            get {
                return ResourceManager.GetString("txtLogin4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that want to confirm this action?.
        /// </summary>
        public static string txtMsgConfirm {
            get {
                return ResourceManager.GetString("txtMsgConfirm", resourceCulture);
            }
        }
    }
}
